Enable tests report

diff --git a/.github/workflows/dotnet-core.yml b/.github/workflows/dotnet-core.yml
--- a/.github/workflows/dotnet-core.yml
+++ b/.github/workflows/dotnet-core.yml
@@ -24,13 +24,13 @@ jobs:
       run: dotnet test --no-restore --logger "trx;LogFileName=tests.trx"
       env:
           Strike__ApiKey: ${{secrets.STRIKE_API_KEY}}
-    #- name: Test Report
-    #  uses: dorny/test-reporter@v1
-    #  if: success() || failure()    # run this step even if previous step failed
-    #  with:
-    #    name: tests
-    #    path: '**/*.trx'
-    #    reporter: dotnet-trx
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: tests
+        path: '**/*.trx'
+        reporter: dotnet-trx
     - name: Pack library project
       run: dotnet pack src/Strike.Client/Strike.Client.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
     - name: Publish library (NuGet)
